# Site settings
title: Parker Tichko
header-img: img/Banner.jpg
email: ""
description: "Website Parker Tichko"
baseurl: ""
url: "https://ptichko.github.io"
twitter_username: parkertichko
github_username:  ptichko

# Google Analytics


# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: [jekyll-paginate, jekyll-feed]
