# Site settings
title: Parker Tichko
header-img: img/Banner.jpg
email: parker.tichko@gmail.edu
description: "Website Parker Tichko"
baseurl: ""
url: "http://ptichko.github.io"
twitter_username: parkertichko
github_username:  ptichko

# Google Analytics


# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate, jekyll-feed]
